version: 2.1

orbs:
  # node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4

jobs:
  just-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      # - docker/check
      - docker/build:
          image: machariavck/ci-testing
      - run: node --version

workflows:
  # testing_this_stuff:
  #   jobs:
  #     - node/test:
  #         version: '18.9.1'
  #         # If you are using yarn, change the line below from "npm" to "yarn"
  #         pkg-manager: npm
  docker_testing:
    jobs:
      - just-build