version: 2.1

orbs:
  # node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4

# jobs:
#   just-build:
#     executor: docker/docker
#     steps:
#       # - setup_remote_docker
#       # - checkout
#       # - docker/check:
#       #     docker-username: D_USER
#       #     docker-password: D_PASS
#       # - docker/build:
#       #     image: $D_USER/ci-testing
#       # - run:
#       #     name: What's my docker creds?
#       #     command: echo username:$D_USER && echo password:$D_PASS
#       # - docker/push:
#       #     digest-path: /tmp/digest.txt
#       #     image: $D_USER/ci-testing
#       - run:
#           command: |
#             echo "Digest is: $(</tmp/digest.txt)" && /
#             echo "GOODNIGHT Champ!"
#       # - run:
#       #     name: Logging in to docker..
#       #     command: |
#       #       echo $D_PASS | docker login --username $D_USER --password-stdin

workflows:
  docker_testing:
    jobs:
      # - just-build
      - docker/publish:
          after_build:
            - run: echo 'build was successful..'
          before_build:
            - run: echo 'build process about to start'
          image: $D_USER/ci-testing
          docker-username: D_USER
          docker-password: D_PASS
          tag: latest
          extra_build_args: --build-arg FOOD --build-arg DRINK