version: 2.1

orbs:
  # node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4

jobs:
  just-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: $DOCKER_LOGIN/ci-testing
      - run:
          name: Logging in to docker..
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: What's my docker creds?
          command: echo username:$DOCKER_LOGIN && echo password:$DOCKER_PASSWORD
      - docker/check

workflows:
  # testing_this_stuff:
  #   jobs:
  #     - node/test:
  #         version: '18.9.1'
  #         # If you are using yarn, change the line below from "npm" to "yarn"
  #         pkg-manager: npm
  docker_testing:
    jobs:
      - just-build