version: 2.1

orbs:
  # node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4

jobs:
  just-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: machariavck/ci-testing
      - run:
          name: What branch am i on now?
          command: echo branch:$CIRCLE_BRANCH
      - run:
          name: What's my docker username?
          command: echo username:$DOCKER_LOGIN
      - run:
          name: What's my docker password?
          command: echo password:$DOCKER_PASSWORD

workflows:
  # testing_this_stuff:
  #   jobs:
  #     - node/test:
  #         version: '18.9.1'
  #         # If you are using yarn, change the line below from "npm" to "yarn"
  #         pkg-manager: npm
  docker_testing:
    jobs:
      - just-build